#
# Module manifest for module 'LeapDNA.Configuration.psm1'
# Generated by: Ganesh Raskar
# Generated on: 11-June-2020
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule        = 'SimplePSLogger.psm1'
    
    # Version of the module. Use this to track when the module was updated.
    ModuleVersion     = '0.0.1'
    
    # ID used to uniquely identify this module''
    GUID              = '4d2e4e26-9ca9-4691-9045-0797a5afa249'

    Author            = 'Ganesh Raskar'
    Copyright         = '2019 Ganesh Raskar. All rights reserved.'
    Description       = 'Experimental logger'
    PowerShellVersion = '5.1.1'

    FunctionsToExport = @(
        'New-SimplePSLogger'
    )
    RequiredModules   = @(
    )

    NestedModules     = @(
        'SimplePSLogger.Console\SimplePSLogger.Console.psm1',
        'SimplePSLogger.File\SimplePSLogger.File.psm1'
    )
		
    PrivateData       = @{
    }

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}